# Generated by Django 4.1 on 2022-10-06 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_category_options_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='course.lesson'),
        ),
    ]
